# Generated by Django 4.2.11 on 2024-03-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Город')),
                ('coordinate_w', models.FloatField(default=0, verbose_name='Ширина')),
                ('coordinate_h', models.FloatField(default=0, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Страна')),
                ('coordinate_w', models.FloatField(default=0, verbose_name='Ширина')),
                ('coordinate_h', models.FloatField(default=0, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страна',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название статуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Статус заведения',
                'verbose_name_plural': 'Статус заведения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Тип заведения')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тип заведения',
                'verbose_name_plural': 'Тип заведения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название магазина')),
                ('default_color', models.CharField(max_length=7, verbose_name='Цвет магазина')),
                ('secondary_color', models.BooleanField(default=True, verbose_name='Вторичный цвет (Белый)')),
                ('description', models.TextField(max_length=500, verbose_name='Описание ресторана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг заведения')),
                ('coordinate_w', models.FloatField(default=0, verbose_name='Ширина')),
                ('coordinate_h', models.FloatField(default=0, verbose_name='Долгота')),
                ('address', models.CharField(max_length=2000, verbose_name='Адрес заведения')),
                ('workTime', models.CharField(max_length=99, verbose_name='Режим работы заведения')),
                ('phoneNumber', models.CharField(max_length=99, verbose_name='Телефон')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_city', to='establishment.city', verbose_name='Город')),
                ('premium_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_establishment_status', to='establishment.premiumstatus', verbose_name='Премиум статус заведения')),
                ('type_of_establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_type_of_establishment', to='establishment.typeofestablishment', verbose_name='Тип заведения')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведение',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='establishment.country', verbose_name='Страна'),
        ),
    ]
