# Generated by Django 4.2.11 on 2024-03-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='additional_code',
            field=models.CharField(blank=True, default='', max_length=99, verbose_name='Альтернативный код'),
        ),
    ]
