# Generated by Django 4.2.11 on 2024-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='backgroundImage',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='default_color',
            field=models.CharField(max_length=7, verbose_name='Цвет заведения'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание заведения'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='title',
            field=models.CharField(max_length=99, verbose_name='Название заведения'),
        ),
    ]
