# Generated by Django 4.2.11 on 2024-03-20 08:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_establishment_backgroundimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Меню')),
                ('photo', models.ImageField(blank=True, upload_to='photos/category/%Y/%m/%d', verbose_name='Изображение')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_menu_establishment', to='establishment.establishment', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Меню заведения',
                'verbose_name_plural': 'Меню заведения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
                ('photo', models.ImageField(blank=True, upload_to='photos/category/%Y/%m/%d', verbose_name='Изображение')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_menu_category_menu', to='establishment.menu', verbose_name='Меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='establishment.menucategory')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название блюда')),
                ('description', models.TextField(max_length=500, verbose_name='Описание блюда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('price', models.FloatField(default=0, verbose_name='Текущая цена')),
                ('old_price', models.FloatField(default=0, verbose_name='Старая цена')),
                ('photo', models.ImageField(blank=True, upload_to='photo/products/%Y/%m/%d', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_news', to='establishment.menucategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюда',
                'verbose_name_plural': 'Блюда',
                'ordering': ['-created_at'],
            },
        ),
    ]
