# Generated by Django 4.2.11 on 2024-03-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_products_additional_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание заведения'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='phoneNumber',
            field=models.CharField(blank=True, default='', max_length=99, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='description',
            field=models.TextField(blank=True, db_index=True, default='', max_length=300, verbose_name='Описание акции'),
        ),
    ]
