# Generated by Django 4.2.11 on 2024-03-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_menu_menucategory_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menu_title'], 'verbose_name': 'Меню заведения', 'verbose_name_plural': 'Меню заведения'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['category_title'], 'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категория меню'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='menu_title',
        ),
        migrations.RenameField(
            model_name='menucategory',
            old_name='title',
            new_name='category_title',
        ),
        migrations.AlterField(
            model_name='menu',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_menu_establishment', to='establishment.establishment', verbose_name='Заведение'),
        ),
    ]
