# Generated by Django 4.2.11 on 2024-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_alter_establishment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='backgroundImage',
            field=models.ImageField(blank=True, upload_to='photos/background/%Y/%m/%d', verbose_name='Фоновое изображение'),
        ),
    ]
