# Generated by Django 4.2.11 on 2025-04-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_alter_establishment_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Рекомендовано'),
        ),
    ]
