# Generated by Django 4.2.11 on 2024-03-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_alter_menu_options_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Временно закончилось'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_products_menu_category', to='establishment.menucategory', verbose_name='Категория'),
        ),
    ]
