# Generated by Django 4.2.11 on 2025-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0005_products_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('color', models.CharField(choices=[('blue', 'blue'), ('gray', 'gray'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow'), ('indigo', 'indigo'), ('purple', 'purple'), ('pink', 'pink')], default='blue', max_length=10, verbose_name='Цвет тега')),
                ('icon', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='establishment',
            name='menu_view_type',
            field=models.CharField(choices=[('Square', 'Квадратные плиты'), ('List', 'Списком'), ('NoImage', 'Без изображений')], default='List', max_length=10, verbose_name='Вид меню'),
        ),
    ]
