# Generated by Django 4.2.11 on 2024-03-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_menu_created_at_menu_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название акции')),
                ('description', models.CharField(db_index=True, max_length=300, verbose_name='Описание акции')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
                ('until_date', models.DateTimeField(verbose_name='Дата истечения срока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-created_at'], 'verbose_name': 'Меню заведения', 'verbose_name_plural': 'Меню заведения'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['-category_title'], 'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категория меню'},
        ),
    ]
