# Generated by Django 4.2.11 on 2025-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_producttag_alter_establishment_menu_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='establishment.producttag', verbose_name='Теги'),
        ),
    ]
