# Generated by Django 4.2.11 on 2025-04-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0007_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='simplified_tags_view',
            field=models.BooleanField(default=False, verbose_name='Упрощенный вид тегов'),
        ),
    ]
