# Generated by Django 4.2.11 on 2024-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0007_promotions_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='until_date',
            field=models.DateField(verbose_name='Дата истечения срока'),
        ),
    ]
