# Generated by Django 4.2.11 on 2024-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_alter_promotions_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='description',
            field=models.TextField(db_index=True, max_length=300, verbose_name='Описание акции'),
        ),
    ]
