# Generated by Django 4.2.11 on 2025-04-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_establishment_simplified_tags_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='establishment.products', verbose_name='Родительский товар'),
        ),
    ]
