# Generated by Django 4.2.11 on 2024-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0009_alter_promotions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='promotion_type',
            field=models.CharField(choices=[('Banner', 'Баннер'), ('Label', 'Надпись')], default='Banner', max_length=10, verbose_name='Тип акции'),
        ),
    ]
