# Generated by Django 4.2.11 on 2025-04-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0009_products_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_parent', to='establishment.products', verbose_name='Родительский товар'),
        ),
    ]
