# Generated by Django 4.2.11 on 2025-04-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0010_alter_products_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='simplified_tags_view',
        ),
        migrations.AddField(
            model_name='establishment',
            name='tags_type_view',
            field=models.CharField(choices=[('FIRST', 'Стандартные'), ('SECOND', 'Упрощенный'), ('THIRD', 'Одним стилем')], default='FIRST', max_length=10, verbose_name='Вид тэгов'),
        ),
    ]
