# Generated by Django 4.2.11 on 2024-03-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0010_promotions_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_promotions_establishment', to='establishment.establishment', verbose_name='Заведение'),
        ),
    ]
