# Generated by Django 4.2.11 on 2024-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0011_promotions_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='promotion_type',
            field=models.CharField(choices=[('Banner', 'Квадратные плиты'), ('Label', 'Списком')], default='Label', max_length=10, verbose_name='Вид меню'),
        ),
    ]
