# Generated by Django 4.2.11 on 2025-04-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0011_remove_establishment_simplified_tags_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_review_establishment', to='establishment.establishment', verbose_name='Заведение'),
        ),
        migrations.CreateModel(
            name='EstablishmentReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=99, verbose_name='IP адрес')),
                ('description', models.TextField(blank=True, db_index=True, default='', max_length=300, verbose_name='Описание акции')),
                ('coordinate_w', models.FloatField(default=0, verbose_name='Ширина')),
                ('coordinate_h', models.FloatField(default=0, verbose_name='Долгота')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_promotions_establishment', to='establishment.establishment', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Отзывы заведений',
                'verbose_name_plural': 'Отзывы заведений',
                'ordering': ['created_at'],
            },
        ),
    ]
