# Generated by Django 4.2.11 on 2024-03-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0012_establishment_promotion_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishment',
            old_name='promotion_type',
            new_name='menu_view_type',
        ),
    ]
