# Generated by Django 4.2.11 on 2024-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0013_rename_promotion_type_establishment_menu_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='menu_view_type',
            field=models.CharField(choices=[('Square', 'Квадратные плиты'), ('List', 'Списком')], default='List', max_length=10, verbose_name='Вид меню'),
        ),
    ]
