# Generated by Django 4.2.11 on 2024-03-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0014_alter_establishment_menu_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_menu_category_establishment', to='establishment.establishment', verbose_name='Заведение'),
        ),
        migrations.AddField(
            model_name='products',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_products_establishment', to='establishment.establishment', verbose_name='Заведение'),
        ),
    ]
