# Generated by Django 4.2.11 on 2024-03-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0015_menucategory_establishment_products_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='tree_id',
        ),
    ]
